# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b72287844888746ac1c4e623f2191fa853935a37ef268f5a4c9b675d08645a62d459accfd634c2aadef31df03b5f1d855bc81aa3ab536b0f8d7f1ec37a17ee20

test:
  secret_key_base: ad86f9888ef7b975a73eaa84bfcc1a8e935127b62d92c6d395657712f64007eb2c08c8fda2304e6933b882a72619be1816038260a28df37e8e0674f8475a8ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
